apiVersion: v1
kind: Service
metadata:
  name: mern-backend-service
  namespace: mern
  labels:
    app: mern-backend
spec:
  selector:
    app: mern-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP

