apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-ingress
  namespace: mern
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - mern.<your-domain>.com
    secretName: mern-tls
  rules:
  - host: mern.<your-domain>.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mern-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mern-backend-service
            port:
              number: 5000

