apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mern
  labels:
    app: mern-backend
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://<username>:<password>@<cluster-url>/mernapp?retryWrites=true&w=majority"
